import { test, expect, type Page } from "@playwright/test";
import { createHash, randomUUID } from "node:crypto";
import { execFileSync } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { createCostingWorkspace, costingScopeSuccessor } from "../helpers/estimating-costing-api";
test.describe.configure({timeout:240000});
test.use({actionTimeout:15000});
async function call(page:Page,path:string,body?:unknown) {
  const r=await page.request.fetch(`/api/v1/${path}`,{method:body===undefined?"GET":"POST",headers:body===undefined?{}:{Origin:"http://127.0.0.1:3000","Content-Type":"application/json"},data:body});
  expect(r.ok(),await r.text()).toBe(true);return r.json();
}
test("E2 browser explicitly adopts exact discovery into manual costs, reconciles an uncertain create and retains old scope through a successor",async({page},info)=>{
  await page.goto("/estimating/discovery");
  await expect(page.getByRole("region",{name:"Local demonstration identity",exact:true})).toHaveAttribute("aria-busy","false");
  if(!(await page.getByLabel("Identity",{exact:true}).isVisible()))await page.getByRole("button",{name:"Change identity",exact:true}).click();
  await page.getByLabel("Identity",{exact:true}).selectOption("coordinator");await page.getByRole("button",{name:"Use this identity",exact:true}).click();
  await expect(page.getByRole("region",{name:"Local demonstration identity",exact:true})).toHaveAttribute("aria-busy","false");
  const api=(path:string,body?:unknown)=>call(page,path,body),s=await createCostingWorkspace(api),title=`SYN Discovery cost ${randomUUID()}`;
  await page.goto(`/estimating/discovery/${s.input.id}`);
  await page.getByRole("link",{name:"Review scope for manual costing",exact:true}).click();
  await page.getByRole("button",{name:"Review selected scope for costing",exact:true}).click();
  await expect(page.getByRole("region",{name:"Reviewed discovery cost basis",exact:true})).toBeVisible();
  await page.getByLabel("Estimate title",{exact:true}).fill(title);
  await page.getByLabel("Included scope",{exact:true}).fill("SYN one manually costed controller");
  await page.getByLabel("Excluded scope",{exact:true}).fill("SYN civil work excluded");
  await page.getByLabel("Assumptions",{exact:true}).fill("SYN independently reviewed manual quantity and price");
  await page.getByRole("button",{name:"Add manual line",exact:true}).click();
  await page.getByLabel("Description 1",{exact:true}).fill("SYN supplied controller");
  await page.getByLabel("Allowance 1",{exact:true}).selectOption("No");
  for(const [label,value] of [["Quantity 1","1"],["Unit 1","each"],["Unit cost AUD 1","120"],["Unit sell AUD 1","175"],["Source 1","SYN internal dated manual source"],["Source date 1","2026-09-01"]])await page.getByLabel(label,{exact:true}).fill(value);
  await page.getByLabel("Reason for adopting this cost basis",{exact:true}).fill("SYN reviewed exact scope for first cost");
  await page.getByRole("checkbox",{name:"I reviewed this exact discovery basis and the manual scope and costs",exact:true}).check();
  let original:Record<string,unknown>|undefined;
  await page.route(`**/api/v1/${s.path}/costing`,async route=>{
    if(route.request().method()!=="POST")return route.continue();original=route.request().postDataJSON();
    const accepted=await route.fetch();expect(accepted.ok()).toBe(true);await route.abort("failed");
  });
  await page.getByRole("button",{name:"Save option estimate",exact:true}).click();
  await expect(page.getByRole("button",{name:"Confirm original save outcome",exact:true})).toBeVisible();
  await expect(page.getByLabel("Estimate title",{exact:true})).toBeDisabled();
  await page.unroute(`**/api/v1/${s.path}/costing`);await page.getByRole("button",{name:"Confirm original save outcome",exact:true}).click();
  await expect(page.getByRole("heading",{name:title,exact:true})).toBeVisible();
  const estimateId=String(original!.estimate_id),first=await api(`estimating/estimates/${estimateId}`);
  expect(first.saved.discovery_basis.revision_id).toBe(s.input.revision_id);expect(first.totals.sell).toBe("175.00");
  await page.reload();await expect(page.getByRole("region",{name:"Saved discovery basis",exact:true})).toContainText("discovery revision 1");
  const successor=await costingScopeSuccessor(api,s);await page.reload();
  await expect(page.getByText("Latest discovery is revision 2 · Complete. It has not replaced this saved cost basis.",{exact:true})).toBeVisible();
  await page.getByRole("link",{name:"Review discovery and explicit scope adoption",exact:true}).click();
  await page.getByRole("link",{name:"Review scope for manual costing",exact:true}).click();
  await page.getByRole("button",{name:"Review selected scope for costing",exact:true}).click();
  await expect(page.getByLabel("Estimate title",{exact:true})).toHaveValue(title);
  await expect(page.getByLabel("Unit sell AUD 1",{exact:true})).toHaveValue("175.00");
  await page.getByLabel("Reason for adopting this cost basis",{exact:true}).fill("SYN retain manual prices and adopt reviewed revised scope");
  await page.getByRole("checkbox",{name:"I reviewed this exact discovery basis and the manual scope and costs",exact:true}).check();
  await page.getByRole("button",{name:"Adopt scope in a new cost version",exact:true}).click();
  await expect(page.getByRole("heading",{name:title,exact:true})).toBeVisible();
  const current=await api(`estimating/estimates/${estimateId}`);expect(current.version).toBe(2);expect(current.saved.discovery_basis.revision_id).toBe(successor.body.revision_id);
  expect((await api(`estimating/estimates/${estimateId}?version_id=${first.saved.id}`)).saved).toEqual(first.saved);
  await page.getByLabel("Draft preparation reason",{exact:true}).fill("SYN exact revised cost version draft");
  await page.getByRole("button",{name:"Prepare draft quotation",exact:true}).click();
  await expect(page.getByRole("article",{name:"Draft quotation preview",exact:true})).toContainText("AUD 175.00");
  await page.getByRole("button",{name:"Generate or recover exact draft",exact:true}).click();
  await expect(page.getByRole("link",{name:"Open exact draft HTML",exact:true})).toBeVisible();
  const quoteId=page.url().split("/").at(-1)!;expect((await api(`estimating/quotes/${quoteId}`)).estimate_version_id).toBe(current.saved.id);
  if(info.project.name.includes("mobile"))await page.setViewportSize({width:320,height:740});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator(".est-paper").evaluate(e=>e.scrollIntoView({block:"start"}));const png=await page.screenshot({path:info.outputPath("E2-cost-basis.png")});
  const checkout=execFileSync("git",["rev-parse","HEAD"],{encoding:"utf8"}).trim();
  await writeFile(info.outputPath("E2-cost-basis.json"),JSON.stringify({source_head:process.env.PPO_SOURCE_HEAD??checkout,executed_checkout:checkout,tree:execFileSync("git",["rev-parse","HEAD^{tree}"],{encoding:"utf8"}).trim(),run_id:process.env.GITHUB_RUN_ID,run_attempt:process.env.GITHUB_RUN_ATTEMPT,viewport:page.viewportSize(),byte_count:png.length,sha256:createHash("sha256").update(png).digest("hex"),estimate_id:estimateId,version_id:current.saved.id,discovery_revision_id:successor.body.revision_id,quote_id:quoteId},null,2));
});
