import { test, expect, type Page, type TestInfo } from "@playwright/test";
import { randomUUID, createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { crmCreate, crmBase } from "../helpers/crm";
import { estimateInput, manualLines, quoteCommand } from "../helpers/estimating";
test.describe.configure({timeout:150000});test.use({actionTimeout:15000});
async function call(page:Page,path:string,body?:unknown){const r=await page.request.fetch(`/api/v1/${path}`,{method:body===undefined?"GET":"POST",headers:body===undefined?{}:{Origin:"http://127.0.0.1:3000","Content-Type":"application/json"},data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();}
async function identity(page:Page,profile="coordinator"){await page.getByLabel("Identity",{exact:true}).selectOption(profile);await page.getByRole("button",{name:"Use this identity",exact:true}).click();await expect(page.getByRole("button",{name:"Use this identity",exact:true})).toBeEnabled();}
async function opportunity(page:Page){await page.goto("/estimating");await identity(page);const o={...crmCreate(),title:`SYN Estimating browser ${randomUUID()}`};await call(page,"crm/opportunities",o);return o;}
async function saved(page:Page){const o=await opportunity(page),input=estimateInput(o.id);await call(page,"estimating/estimates",input);await page.goto(`/estimating/estimates/${input.id}`);await expect(page.getByRole("heading",{name:"Scope and cost workbook"})).toBeVisible();return input;}
async function capture(page:Page,info:TestInfo,name:string,anchor=".est-heading"){
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator(anchor).first().evaluate(e=>e.scrollIntoView({block:"start"}));
  const bytes=await page.screenshot({path:info.outputPath(`E1-${name}.png`)});
  await writeFile(info.outputPath(`E1-${name}.json`),JSON.stringify({name,viewport:page.viewportSize(),source_head:process.env.PPO_SOURCE_HEAD,checkout:execFileSync("git",["rev-parse","HEAD"],{encoding:"utf8"}).trim(),run_id:process.env.GITHUB_RUN_ID,sha256:createHash("sha256").update(bytes).digest("hex")},null,2));
}
test("E1 browser: create through UI, save successor, prepare hidden allowance, generate and reopen exact draft",async({page},info)=>{
  const o=await opportunity(page);await page.goto("/estimating/new");await page.getByLabel("Existing opportunity",{exact:true}).selectOption(o.id);
  await page.getByLabel("Estimate title",{exact:true}).fill("SYN Browser controls estimate");await page.getByLabel("Included scope",{exact:true}).fill("SYN Supply controls and install at the permitted site.");await page.getByLabel("Excluded scope",{exact:true}).fill("Civil works excluded.");await page.getByLabel("Assumptions",{exact:true}).fill("Fictional prices for review.");
  const lines=manualLines();
  for(let i=0;i<lines.length;i++){const n=i+1,l=lines[i];await page.getByRole("button",{name:"Add manual line",exact:true}).click();for(const [label,value] of [[`Description ${n}`,l.description],[`Quantity ${n}`,l.quantity],[`Unit ${n}`,l.unit],[`Unit cost AUD ${n}`,l.unit_cost],[`Unit sell AUD ${n}`,l.unit_sell],[`Source ${n}`,l.source],[`Source date ${n}`,l.effective_date]])await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel(`Category ${n}`,{exact:true}).selectOption(l.category);}
  await expect(page.getByRole("complementary",{name:"Proposal totals"})).toContainText("AUD 720.00");await capture(page,info,"proposal",".est-line");
  await page.getByLabel("Reason for creating this estimate",{exact:true}).fill("SYN Initial manual estimate");await page.getByRole("button",{name:"Create estimate",exact:true}).click();await expect(page).toHaveURL(/\/estimating\/estimates\//);
  await page.getByLabel("Quantity 1",{exact:true}).fill("3");await page.getByLabel("Change reason",{exact:true}).fill("SYN Add third controller");await page.getByRole("button",{name:"Save new version",exact:true}).click();await expect(page.getByText(/Viewing saved version 2/)).toBeVisible();await expect(page.getByLabel("Quantity 1",{exact:true})).toHaveValue("3.000");
  await page.reload();await expect(page.getByText(/Viewing saved version 2/)).toBeVisible();await capture(page,info,"saved-estimate");
  await page.getByLabel("Print SYN Installation labour",{exact:true}).uncheck();await page.getByLabel("Draft preparation reason",{exact:true}).fill("SYN Review exact saved scope");await page.getByRole("button",{name:"Prepare draft quotation",exact:true}).click();await expect(page).toHaveURL(/\/estimating\/quotes\//);
  await expect(page.getByRole("article",{name:"Draft quotation preview"})).toContainText("Included scope allowance");await expect(page.getByRole("article",{name:"Draft quotation preview"})).not.toContainText("private supplier");
  await page.getByRole("button",{name:"Generate or recover exact draft",exact:true}).click();await expect(page.getByRole("link",{name:"Open draft PDF",exact:true})).toBeVisible({timeout:60000});await capture(page,info,"draft-output");
  const href=await page.getByRole("link",{name:"Open exact draft HTML",exact:true}).getAttribute("href");const before=await page.request.get(href!);expect(before.ok()).toBe(true);const original=await before.body();await page.reload();const after=await page.request.get(href!);expect(await after.body()).toEqual(original);
  expect(original.toString()).toContain("AUD 895.00");await page.goto(href!);await expect(page.getByRole("img",{name:"Powerplants Australia"})).toBeVisible();expect(await page.getByRole("img").evaluate(e=>e.getBoundingClientRect().height)).toBe(88);await capture(page,info,"exact-html","header");
});
test("E1 browser: rejected decimal retains proposal and shows no saved claim",async({page},info)=>{
  await saved(page);await page.getByLabel("Unit cost AUD 1",{exact:true}).fill("NaN");await page.getByLabel("Change reason",{exact:true}).fill("SYN Invalid proposal check");await page.getByRole("button",{name:"Save new version",exact:true}).click();await expect(page.locator('.business-error[role="alert"]')).toContainText("decimal");await expect(page.getByLabel("Unit cost AUD 1",{exact:true})).toHaveValue("NaN");await expect(page.getByRole("complementary",{name:"Proposal totals"})).toContainText("Unknown");await capture(page,info,"validation",'.business-error[role="alert"]');
});
test("E1 browser: changed version preserves proposal until explicit comparison baseline",async({page},info)=>{
  const input=await saved(page);await page.getByLabel("Quantity 1",{exact:true}).fill("5");const server={...crmBase(),expected_version:1,title:input.title,scope:input.scope,lines:input.lines.map(l=>({...l,quantity:"3"})),policy:input.policy};await call(page,`estimating/estimates/${input.id}`,server);
  await page.getByLabel("Change reason",{exact:true}).fill("SYN Retain my five units after comparison");await page.getByRole("button",{name:"Save new version",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"changed"}).first()).toBeVisible();await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await expect(page.getByText("Compare current saved version 2 with this proposal",{exact:true})).toBeVisible();await expect(page.getByLabel("Quantity 1",{exact:true})).toHaveValue("5");await page.getByText("Compare current saved version 2 with this proposal",{exact:true}).click();await capture(page,info,"conflict",'#estimate-work');await page.getByRole("button",{name:"Keep my proposal and use current version as its predecessor",exact:true}).click();await page.getByRole("button",{name:"Save new version",exact:true}).click();await expect(page.getByText(/Viewing saved version 3/)).toBeVisible();
});
test("E1 browser: lost accepted response reconciles original operation before new intent",async({page},info)=>{
  const input=await saved(page);let lost=false;
  await page.route(`**/api/v1/estimating/estimates/${input.id}`,async route=>{if(route.request().method()==="POST"&&!lost){lost=true;const r=await route.fetch();expect(r.ok()).toBe(true);await route.abort("failed");}else await route.continue();});
  await page.getByLabel("Quantity 1",{exact:true}).fill("7");await page.getByLabel("Change reason",{exact:true}).fill("SYN Lost response original");await page.getByRole("button",{name:"Save new version",exact:true}).click();await expect(page.getByRole("button",{name:"Confirm original save outcome",exact:true})).toBeVisible();await expect(page.getByLabel("Quantity 1",{exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:"Prepare draft quotation",exact:true})).toBeDisabled();await capture(page,info,"uncertain",'.business-error[role="alert"]');await page.getByRole("button",{name:"Confirm original save outcome",exact:true}).click();await expect(page.getByText(/Viewing saved version 2/)).toBeVisible();expect((await call(page,`estimating/estimates/${input.id}`)).versions.length).toBe(2);
});
test("E1 browser: identity loss clears sensitive workbook; 320px controls and long draft reflow",async({page},info)=>{
  const input=await saved(page);await page.setViewportSize({width:320,height:844});await capture(page,info,"phone-320-workbook",".est-line");await page.getByLabel("Quantity 1",{exact:true}).focus();await expect(page.getByLabel("Quantity 1",{exact:true})).toBeFocused();await identity(page,"systems");await expect(page.locator('.business-error[role="alert"]')).toContainText("This record is unavailable.");await expect(page.getByLabel("Unit cost AUD 1",{exact:true})).toHaveCount(0);await expect(page.getByText("SYN private supplier cost note — internal only",{exact:true})).toHaveCount(0);await capture(page,info,"denied",'.business-error[role="alert"]');
  await identity(page);const d=await call(page,`estimating/estimates/${input.id}`),long={...crmBase(),expected_version:1,title:"SYN Long draft output",scope:{included:"Synthetic multiline included scope.\n".repeat(60),excluded:"Excluded synthetic work.\n".repeat(40),assumptions:"Fictional review assumption.\n".repeat(40)},lines:Array.from({length:24},(_,i)=>({...input.lines[i%3],id:randomUUID(),description:`SYN item ${i+1} ${"Long unbroken description ".repeat(7)}`})),policy:input.policy};await call(page,`estimating/estimates/${input.id}`,long);const current=await call(page,`estimating/estimates/${input.id}`);expect(d.version).toBe(1);const q=quoteCommand(current.saved,2);q.choices=q.choices.map(c=>({...c,print:true}));await call(page,`estimating/estimates/${input.id}/quotes`,q);await call(page,`estimating/quotes/${q.id}/render`,{});
  const pdf=await page.request.get(`/api/v1/estimating/quotes/${q.id}/file?kind=pdf`);expect(pdf.ok()).toBe(true);await writeFile(info.outputPath("E1-long-draft.pdf"),await pdf.body());await page.goto(`/api/v1/estimating/quotes/${q.id}/file?kind=html`);await capture(page,info,"phone-320-long-draft","table");
});
