import { randomUUID } from 'node:crypto';
import type { Principal } from '../platform/identity';
import { database } from '../platform/database';
import { sharedOperation } from '../platform/operations';
import { AppError } from '../platform/errors';
import { insert } from '../documents/packs';
import { documentStore,digest } from '../documents/store';
import { sameVersion } from '../scheduling/validation';
import { common,commonKeys,object,uuid,version } from '../shared/validation';
import { attendanceContext,attachmentContext } from './context';
import { attachmentCommand } from './validation';
import { inspectPng } from './media';
export async function initiateAttachment(p:Principal,input:unknown){const cmd=attachmentCommand(input);return sharedOperation(p,cmd,'InitiateFieldAttachment',c=>attendanceContext(c,p,cmd.appointment_id,cmd.attendance_id,'field.attachment.own'),async(c,ctx)=>{const row=await insert(c,'field_attachments',{id:cmd.id,workspace_id:p.workspace_id,company_id:ctx.a.company_id,site_id:ctx.a.site_id,appointment_id:ctx.a.id,actor_id:p.actor_id,attendance_id:ctx.attendance.id,upload_operation_id:cmd.operation_id,storage_item_id:randomUUID(),filename:cmd.filename,media_type:cmd.media_type,byte_count:cmd.byte_count,content_hash:cmd.content_hash});await insert(c,'field_attachment_events',{workspace_id:p.workspace_id,attachment_id:row.id,actor_id:p.actor_id,status:'Pending'});return {id:row.id,version:row.version,state:row.status,updated_at:row.received_at,audit_details:{appointment_id:ctx.a.id,upload_operation_id:cmd.operation_id}};},'Attachment','AttachmentInitiated');}
function fileKey(a:{storage_item_id:string;content_hash:string}){return {provider:'Synthetic' as const,tenant_id:null,site_id:null,drive_id:null,item_id:a.storage_item_id,version_id:a.content_hash,sha256:a.content_hash};}
export async function verifiedAttachmentBytes(p:Principal,a:{storage_item_id:string;content_hash:string;byte_count:number}){const bytes=Buffer.from(await documentStore().read({...p,operation_id:a.storage_item_id},fileKey(a)));if(bytes.length!==a.byte_count||digest(bytes)!==a.content_hash)throw new AppError(503,'AttachmentUnavailable','The original photo bytes need recovery. Their reference is retained.');inspectPng(bytes);return bytes;}
export async function uploadAttachment(p:Principal,id:string,input:unknown,hooks:{afterStore?:()=>Promise<void>}={}){
 const r=object(input,[...commonKeys,'expected_version','content_base64']);if(typeof r.content_base64!=='string'||r.content_base64.length>5592408||(r.content_base64.length%4!==0||! /^[A-Za-z0-9+/]*={0,2}$/.test(r.content_base64)))throw new AppError(422,'InvalidImageTransfer','Transfer the complete bounded PNG bytes.');
 const bytes=Buffer.from(r.content_base64,'base64'),cmd={...common(r),id:uuid(id,'attachment_id'),expected_version:version(r.expected_version),byte_count:bytes.length,sha256:digest(bytes)};
 return sharedOperation(p,cmd,'UploadFieldAttachment',c=>attachmentContext(c,p,id,true),async(c,{attachment:a})=>{
 sameVersion(a.version,cmd.expected_version,'photo');if(a.status!=='Pending')throw new AppError(409,'AttachmentStateConflict','Recover the original upload or begin a distinct photo.');if(bytes.length!==a.byte_count||cmd.sha256!==a.content_hash)throw new AppError(422,'AttachmentHashMismatch','Transferred bytes do not match the original size and hash. Retry the original photo.');
 let status='Uploaded',dimensions:{width:number;height:number}|null=null;try{dimensions=inspectPng(bytes);}catch(e){if(!(e instanceof AppError))throw e;status='Rejected';}
 if(status==='Uploaded'){await documentStore().store({...p,operation_id:a.storage_item_id},bytes,a.content_hash);await verifiedAttachmentBytes(p,a);await hooks.afterStore?.();}
 const saved=(await c.query('UPDATE ppo.field_attachments SET version=version+1,status=$3,width=$4,height=$5,storage_version=$6,error_code=$7 WHERE workspace_id=$1 AND id=$2 RETURNING *',[p.workspace_id,id,status,dimensions?.width??null,dimensions?.height??null,status==='Uploaded'?a.content_hash:null,status==='Rejected'?'UnsupportedImage':null])).rows[0];await insert(c,'field_attachment_events',{workspace_id:p.workspace_id,attachment_id:id,actor_id:p.actor_id,status,code:saved.error_code});return {id,version:saved.version,state:status,updated_at:new Date(),audit_details:{appointment_id:a.appointment_id,upload_operation_id:a.upload_operation_id,byte_count:a.byte_count,content_hash:a.content_hash}};
 },'Attachment','AttachmentUploaded');
}
export async function finaliseAttachment(p:Principal,id:string,input:unknown){const r=object(input,[...commonKeys,'expected_version']),cmd={...common(r),id:uuid(id,'attachment_id'),expected_version:version(r.expected_version)};return sharedOperation(p,cmd,'FinaliseFieldAttachment',c=>attachmentContext(c,p,id,true),async(c,{attachment:a})=>{
 sameVersion(a.version,cmd.expected_version,'photo');if(!['Uploaded','Quarantined'].includes(a.status))throw new AppError(422,'AttachmentNotUploaded','Upload and verify the original photo bytes first.');let status='Available',code:string|null=null;try{await verifiedAttachmentBytes(p,a);}catch(e){if(!(e instanceof AppError))throw e;status='Quarantined';code='ExactBytesUnavailable';}
 const saved=(await c.query('UPDATE ppo.field_attachments SET version=version+1,status=$3,verified_at=CASE WHEN $3=\'Available\' THEN clock_timestamp() ELSE NULL END,error_code=$4 WHERE workspace_id=$1 AND id=$2 RETURNING *',[p.workspace_id,id,status,code])).rows[0];await insert(c,'field_attachment_events',{workspace_id:p.workspace_id,attachment_id:id,actor_id:p.actor_id,status,code});return {id,version:saved.version,state:status,updated_at:new Date(),audit_details:{appointment_id:a.appointment_id,upload_operation_id:a.upload_operation_id,content_hash:a.content_hash}};
 },'Attachment','AttachmentFinalised');}
export async function attachmentMetadata(p:Principal,id:string){const {attachment:a}=await attachmentContext(database(),p,id);let retrieval_verified=false;if(a.status==='Available')try{await verifiedAttachmentBytes(p,a);retrieval_verified=true;}catch(e){if(!(e instanceof AppError))throw e;}return {id:a.id,appointment_id:a.appointment_id,actor_id:a.actor_id,filename:a.filename,media_type:a.media_type,byte_count:a.byte_count,sha256:a.content_hash,version:a.version,status:a.status,width:a.width,height:a.height,access_class:a.access_class,received_at:a.received_at,verified_at:a.verified_at,error_code:a.error_code,retrieval_verified};}
export async function attachmentBytes(p:Principal,id:string){const {attachment:a}=await attachmentContext(database(),p,id);if(a.status!=='Available')throw new AppError(422,'AttachmentUnavailable','This photo is not yet available. Its original upload remains recoverable.');return {bytes:await verifiedAttachmentBytes(p,a),filename:`SYN-photo-${a.id}.png`};}
