"use client";
import Link from "next/link";
import { useEffect, useLayoutEffect, useRef, useState, type CSSProperties } from "react";
import { ProductIcon } from "./product-icons";
import { dealAmount, dealClose, useDesktopCRM } from "./crm-deal-controls";
import { Stamp } from "./business-ui";
import type { listOpportunities, WorklistItem } from "../crm/worklist";
import { actionLabels, needsAttention } from "../crm/worklist-presentation";

type Results = Awaited<ReturnType<typeof listOpportunities>>;
type Scroll = { read: () => { top: number; left: number }; save: (top: number, left: number) => void };
const initials = (name: string) => name.split(/\s+/).filter(Boolean).slice(-2).map(word => word[0]).join("").toUpperCase();
function Owners({ item }: { item: WorklistItem }) {
  return <div className="crm-card-owners"><span className="crm-owner-avatar" tabIndex={0} title={`Opportunity owner: ${item.owner_name}`} aria-label={`Opportunity owner: ${item.owner_name}`}>{initials(item.owner_name)}</span>{item.action_owner_name && <span className="crm-owner-avatar crm-activity-avatar" tabIndex={0} title={`Activity owner: ${item.action_owner_name}`} aria-label={`Activity owner: ${item.action_owner_name}`}>{initials(item.action_owner_name)}</span>}</div>;
}
function CardActivity({ item, onActivity }: { item: WorklistItem; onActivity: (item: WorklistItem) => void }) {
  return <button type="button" className={`crm-card-activity state-${item.next_action_state}`} draggable={false} aria-haspopup="dialog" onClick={() => onActivity(item)}><ProductIcon name="calendar"/><span className="crm-activity-copy"><span className="crm-action-text">{item.next_action_state === "Needed" ? "Nothing scheduled" : item.next_action_summary ?? "Activity unavailable"}</span><small>{item.next_action_state === "Needed" ? "Schedule a follow-up" : item.due_at ? <><span>{item.next_action_state === "Overdue" ? "Overdue · " : "Due · "}</span><Stamp value={item.due_at}/></> : actionLabels[item.next_action_state]}</small></span></button>;
}

export function Board({ data, selected, scroll, onOpen, onStage, blocked, onMove, onActivity, onEdit, onOutcome }: { data: Results; selected: string; scroll: Scroll; onOpen: (id: string) => void; onStage: (id: string) => void; blocked: boolean; onMove: (id: string, stage: string) => void; onActivity: (item: WorklistItem) => void; onEdit: (id: string) => void; onOutcome: (id: string) => void }) {
  const desktop = useDesktopCRM(), drag = useRef<string | null>(null), suppress = useRef(0), [destination, setDestination] = useState<string | null>(null), [dragging, setDragging] = useState(false), [collapsed, setCollapsed] = useState<string[]>([]);
  const ref = useRef<HTMLDivElement>(null);
  const endDrag = () => { drag.current = null; setDestination(null); setDragging(false); suppress.current = Date.now() + 400; };
  useEffect(() => { const cancel = (e: KeyboardEvent) => { if (e.key === "Escape" && drag.current) endDrag(); }; document.addEventListener("keydown", cancel); return () => document.removeEventListener("keydown", cancel); }, []);
  useLayoutEffect(() => { if (ref.current) { const saved = scroll.read(); ref.current.scrollTop = saved.top; ref.current.scrollLeft = saved.left; } }, [scroll]);
  const tracks = data.stages.map(stage => desktop && collapsed.includes(stage.stage_id) ? "64px" : "minmax(0,1fr)").join(" ");
  const collapse = (stage: string) => setCollapsed(old => old.includes(stage) ? old.filter(id => id !== stage) : [...old, stage]);
  return <><div ref={ref} className="crm-board-scroll" role="region" aria-label="Opportunity Board — stage sequence" tabIndex={0} onScroll={e => scroll.save(e.currentTarget.scrollTop, e.currentTarget.scrollLeft)}>
    <div className="crm-board" style={{ "--crm-stage-count": data.stages.length, "--crm-stage-tracks": tracks } as CSSProperties}>
      <div className="crm-board-headers">{data.stages.map(stage => <header key={stage.stage_id} className="crm-stage-heading" data-selected={stage.stage_id === selected} data-collapsed={desktop && collapsed.includes(stage.stage_id)} data-drop-active={destination === stage.stage_id}>
        <div className="crm-stage-heading-copy"><h2 id={`board-${stage.stage_id}`}>{stage.stage_id}</h2><div className="crm-stage-total"><span>{stage.count} {stage.count === 1 ? "deal" : "deals"}</span></div></div>
        {desktop && <button type="button" className="secondary crm-collapse-stage" onClick={() => collapse(stage.stage_id)} aria-label={`${collapsed.includes(stage.stage_id) ? "Expand" : "Collapse"} ${stage.stage_id}`} aria-expanded={!collapsed.includes(stage.stage_id)}><ProductIcon name={collapsed.includes(stage.stage_id) ? "expand" : "collapse"}/></button>}
      </header>)}</div>
      <div className="crm-board-columns">{data.stages.map(stage => <section key={stage.stage_id} className="crm-stage" data-selected={stage.stage_id === selected} data-collapsed={desktop && collapsed.includes(stage.stage_id)} data-drop-stage={stage.stage_id} data-drop-active={destination === stage.stage_id} aria-labelledby={`board-${stage.stage_id}`}
        onDragOver={e => { if (!desktop || !drag.current) return; e.preventDefault(); e.dataTransfer.dropEffect = "move"; setDestination(stage.stage_id); const node = ref.current, bounds = node?.getBoundingClientRect(); if (node && bounds) { if (e.clientY < bounds.top + 90) node.scrollTop -= 12; else if (e.clientY > bounds.bottom - 40) node.scrollTop += 12; } }}
        onDrop={e => { if (!desktop || !drag.current) return; e.preventDefault(); const id = drag.current; endDrag(); onMove(id, stage.stage_id); }}>
        {desktop && collapsed.includes(stage.stage_id) ? <button className="secondary crm-collapsed-rail" onClick={() => collapse(stage.stage_id)} aria-label={`Expand ${stage.stage_id} column`}>{stage.stage_id} · {stage.count}</button> : <><ul className="crm-worklist">{data.items.filter(item => item.stage_id === stage.stage_id).map(item => <li key={item.id} data-opportunity-id={item.id} className="crm-card" data-health={item.next_action_state} draggable={desktop && item.can_edit && item.close_outcome === "Open" && !blocked}
          onDragStart={e => { if (!desktop || blocked || !item.can_edit || item.close_outcome !== "Open" || (e.target as HTMLElement).closest("button,.crm-card-footer")) { e.preventDefault(); return; } drag.current = item.id; setDragging(true); e.dataTransfer.effectAllowed = "move"; e.dataTransfer.setData("text/x-ppo-opportunity", item.id); }} onDragEnd={endDrag}>
          <Link className="crm-card-body crm-opportunity-title" href={`/crm/opportunities/${item.id}`} aria-label={item.title} draggable={false} onClick={e => { if (Date.now() < suppress.current) e.preventDefault(); }}>
            <span className="crm-card-heading"><span className="crm-card-title" title={item.title}>{item.title}</span>{item.close_outcome !== "Open" && <span>{item.close_outcome}</span>}</span>
            <span className="crm-card-company" title={item.organisation_name}>{item.organisation_name}</span>
            <span className="crm-card-contact" title={`Primary contact: ${item.contact_name ?? "Not yet identified"}`}>{item.contact_name ?? "No primary contact"}</span>
            <span className="crm-card-value"><span className="crm-card-close"><ProductIcon name="flag"/>{dealClose(item.expected_close_date)}</span><strong>{dealAmount(item.value_amount)}</strong></span>
          </Link>
          {needsAttention(item) && <button className="crm-card-warning" aria-label={`${actionLabels[item.next_action_state]} for ${item.title}. Plan an activity`} title={actionLabels[item.next_action_state]} onClick={() => onActivity(item)}><ProductIcon name="warning"/></button>}
          <CardActivity item={item} onActivity={onActivity}/>
          <button className={`crm-card-health state-${item.next_action_state}`} onClick={() => onActivity(item)}><ProductIcon name={needsAttention(item) ? "warning" : item.next_action_state === "Unavailable" ? "info" : "check"}/>{actionLabels[item.next_action_state]}</button>
          <div className="crm-card-footer"><Owners item={item}/><div className="crm-card-shortcuts" role="group" aria-label={`Quick actions for ${item.title}`}>
            <button className="secondary" title="Snapshot" aria-label={`Snapshot: ${item.title}`} onClick={() => onOpen(item.id)}><ProductIcon name="eye"/></button>
            <Link title="Linked activities" aria-label={`Activities: ${item.title}`} href={`/crm/opportunities/${item.id}?section=timeline`}><ProductIcon name="work"/></Link>
            <Link title="Documents" aria-label={`Documents: ${item.title}`} href={`/crm/opportunities/${item.id}?section=files`}><ProductIcon name="documents"/></Link>
            <button className="secondary" title="Next activity" aria-label={`Next activity: ${item.title}`} onClick={() => onActivity(item)}><ProductIcon name="calendar"/></button>
            {item.can_edit && item.close_outcome === "Open" && <><button type="button" className="secondary crm-card-stage" aria-label={`Change stage for ${item.title}`} title="Change stage" aria-haspopup="dialog" disabled={blocked} draggable={false} onClick={() => onStage(item.id)}><ProductIcon name="board"/></button><button className="secondary" title="Edit opportunity" aria-label={`Edit opportunity: ${item.title}`} disabled={blocked} onClick={() => onEdit(item.id)}><ProductIcon name="edit"/></button></>}
          </div></div>
        </li>)}</ul>{stage.count === 0 && <p className="crm-stage-empty">No {stage.stage_id.toLowerCase()} opportunities on this page.</p>}</>}
      </section>)}</div>
    </div>
  </div>{dragging && <div className="crm-drag-actions" aria-label="Drop actions">{(["Delete", "Lost", "Won", "Move"] as const).map(action => <div key={action} data-disabled={action === "Delete"} title={action === "Delete" ? "Deletion is not available in this app" : "Opens the saved workflow for review"} onDragOver={e => { if (action !== "Delete") e.preventDefault(); }} onDrop={e => { if (action === "Delete" || !drag.current) return; e.preventDefault(); const id = drag.current; endDrag(); if (action === "Move") onStage(id); else onOutcome(id); }}><ProductIcon name={action === "Delete" ? "trash" : action === "Move" ? "board" : action === "Won" ? "check" : "close"}/>{action}</div>)}</div>}</>;
}

const columns = ["Opportunity", "Organisation", "Primary contact", "Value", "Expected close", "Stage / outcome", "Owner", "Next activity"];
export function Grid({ data, scroll, onOpen }: { data: Results; scroll: Scroll; onOpen: (id: string) => void }) {
  const ref = useRef<HTMLDivElement>(null), [widths, setWidths] = useState([280, 210, 175, 140, 155, 170, 175, 270]);
  useLayoutEffect(() => { if (ref.current) { const saved = scroll.read(); ref.current.scrollTop = saved.top; ref.current.scrollLeft = saved.left; } }, [scroll]);
  return <div ref={ref} className="crm-grid-scroll" role="region" aria-label="Opportunity List — scroll for all columns" tabIndex={0} onScroll={e => scroll.save(e.currentTarget.scrollTop, e.currentTarget.scrollLeft)}><table className="crm-grid crm-r38-grid" style={{ width: widths.reduce((a, b) => a + b, 0) }}><caption className="sr-only">Permitted opportunities on this page · {data.items.length} rows · {data.sort} order</caption><colgroup>{widths.map((width, i) => <col key={i} style={{ width }}/>)}</colgroup><thead><tr>{columns.map((column, i) => <th key={column} scope="col" aria-label={column}>{column}<button className="crm-column-resize" aria-label={`Resize ${column} column`} onKeyDown={e => { if (["ArrowLeft", "ArrowRight"].includes(e.key)) { e.preventDefault(); setWidths(old => old.map((w, j) => j === i ? Math.max(110, Math.min(600, w + (e.key === "ArrowRight" ? 20 : -20))) : w)); } }} onPointerDown={e => { e.preventDefault(); e.currentTarget.setPointerCapture(e.pointerId); e.currentTarget.dataset.startX = String(e.clientX); e.currentTarget.dataset.startWidth = String(widths[i]); }} onPointerMove={e => { if (!e.currentTarget.hasPointerCapture(e.pointerId)) return; const width = Math.max(110, Math.min(600, Number(e.currentTarget.dataset.startWidth) + e.clientX - Number(e.currentTarget.dataset.startX))); setWidths(old => old.map((w, j) => j === i ? width : w)); }} onPointerUp={e => { if (e.currentTarget.hasPointerCapture(e.pointerId)) e.currentTarget.releasePointerCapture(e.pointerId); }}/></th>)}</tr></thead><tbody>{data.items.map(item => <tr key={item.id} data-opportunity-id={item.id}><th scope="row"><Link className="crm-opportunity-title" href={`/crm/opportunities/${item.id}`}>{item.title}</Link><small>{item.display_number}</small><button className="secondary crm-list-snapshot" aria-label={`Snapshot: ${item.title}`} onClick={() => onOpen(item.id)}><ProductIcon name="eye"/></button></th><td>{item.organisation_name}</td><td>{item.contact_name ?? "Not recorded"}</td><td>{dealAmount(item.value_amount)}</td><td>{dealClose(item.expected_close_date)}</td><td>{item.stage_id}<p>{item.close_outcome}</p></td><td>{item.owner_name}</td><td><strong>{actionLabels[item.next_action_state]}</strong><p className="crm-action-text">{item.next_action_summary}</p><small>Action owner: {item.action_owner_name}</small></td></tr>)}</tbody></table>{!data.items.length && <p className="crm-empty-results">No opportunities match these filters.</p>}</div>;
}
