"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import type { estimatingOptions, listEstimates, readEstimate, readQuote } from "../estimating/reads";
import { arithmeticPolicy, calculate, quoteAmounts, type CostLine, type QuoteChoice } from "../estimating/math";
import { parseLines } from "../estimating/validation";
import { ErrorNotice, Field, SelectField, ValidationFields, api, PageHeader, Status } from "./business-ui";
import { denied, useCrmResource, useCrmCommand } from "./crm-state";
import "./estimating.css";
type Detail=Awaited<ReturnType<typeof readEstimate>>;
type Quote=Awaited<ReturnType<typeof readQuote>>;
type Options=Awaited<ReturnType<typeof estimatingOptions>>;
type Draft={title:string;scope:{included:string;excluded:string;assumptions:string};lines:CostLine[]};
const money=(v:string|null|undefined)=>v==null?"Unknown":`AUD ${v}`;
function ResourceState({loading,error,reload}:{loading:boolean;error:unknown;reload:()=>void}) {
  return <><ErrorNotice error={error}/>{loading&&<p role="status">Loading permitted estimating records…</p>}{error!=null&&<button className="secondary" onClick={reload}>Try loading again</button>}</>;
}
function CommandState({command}:{command:ReturnType<typeof useCrmCommand>}) {
  const failure=command.error as {field_errors?:{field:string;message:string}[]}|null;
  const displayError=failure?{...failure,field_errors:failure.field_errors?.map(e=>({...e,field:e.field.replace(/^lines\.(\d+)\./,(_m,n:string)=>`Line ${Number(n)+1} `)}))}:null;
  return <><p role="status">{command.status}</p><ErrorNotice error={displayError}/>{command.uncertain&&<button disabled={command.busy} onClick={()=>void command.reconcile()}>Confirm original save outcome</button>}</>;
}
function Heading({title,children}:{title:string;children?:React.ReactNode}) {
  return <PageHeader eyebrow="Estimating · Synthetic" title={title} action={children}/>;
}
export function EstimateList() {
  const data=useCrmResource<Awaited<ReturnType<typeof listEstimates>>>("estimating/estimates");
  return <div className="est-screen"><Heading title="Estimates">{data.data?.can_create&&<Link className="button" href="/estimating/new">New estimate</Link>}</Heading><p>Manual estimates and draft quotations, linked to the existing sales opportunity.</p><ResourceState {...data}/>{data.data&&<><p>Showing up to {data.data.limit} permitted estimates, most recently saved first.</p>{!data.data.items.length?<div className="est-panel"><h2>No estimates yet</h2><p>Start from an existing opportunity and record the scope, assumptions and manual pricing basis.</p><Link href="/crm/opportunities">Open CRM Sales</Link></div>:<div className="est-list">{data.data.items.map(e=><article className="est-panel" key={e.id}><div><p className="est-eyebrow">{e.display_number} · Saved version {e.version} · Draft</p><h2><Link href={`/estimating/estimates/${e.id}`}>{e.title}</Link></h2><p>{e.customer}</p></div><div><small>Saved sell · excluding tax</small><strong>{money(e.sell_total)}</strong></div></article>)}</div>}</>}</div>;
}
function DraftFields({value,onChange}:{value:Draft;onChange:(v:Draft)=>void}) {
  const set=(key:keyof Draft,v:Draft[keyof Draft])=>onChange({...value,[key]:v});
  const line=(index:number,patch:Partial<CostLine>)=>set("lines",value.lines.map((l,i)=>i===index?{...l,...patch}:l));
  return <><Field label="Estimate title" name="title" value={value.title} onChange={v=>set("title",v)} required maxLength={200}/><div className="est-scope"><Field label="Included scope" name="included" value={value.scope.included} onChange={v=>set("scope",{...value.scope,included:v})} multiline required maxLength={3000}/><Field label="Excluded scope" name="excluded" value={value.scope.excluded} onChange={v=>set("scope",{...value.scope,excluded:v})} multiline required maxLength={2000}/><Field label="Assumptions" name="assumptions" value={value.scope.assumptions} onChange={v=>set("scope",{...value.scope,assumptions:v})} multiline required maxLength={2000}/></div><h2 id="estimate-lines">Manual cost lines</h2><p>Each line needs a quantity and unit, cost, sell price, source and source date. Blank amounts remain unknown. Up to 100 lines.</p>{value.lines.map((l,i)=><fieldset key={l.id} className="est-line"><legend>Line {i+1} · {l.category}</legend><div className="est-line-main"><Field label={`Description ${i+1}`} name={`lines.${i}.description`} value={l.description} onChange={v=>line(i,{description:v})} required maxLength={300}/><SelectField label={`Category ${i+1}`} name={`lines.${i}.category`} value={l.category} onChange={v=>line(i,{category:v as CostLine["category"]})} options={["Product","Labour","Freight"].map(id=>({id,display_name:id}))} required/><Field label={`Quantity ${i+1}`} name={`lines.${i}.quantity`} value={l.quantity} onChange={v=>line(i,{quantity:v})} required hint="Up to 3 decimal places"/><Field label={`Unit ${i+1}`} name={`lines.${i}.unit`} value={l.unit} onChange={v=>line(i,{unit:v})} required maxLength={40}/><Field label={`Unit cost AUD ${i+1}`} name={`lines.${i}.unit_cost`} value={l.unit_cost} onChange={v=>line(i,{unit_cost:v})} required/><Field label={`Unit sell AUD ${i+1}`} name={`lines.${i}.unit_sell`} value={l.unit_sell} onChange={v=>line(i,{unit_sell:v})} required/></div><div className="est-line-basis"><Field label={`Source ${i+1}`} name={`lines.${i}.source`} value={l.source} onChange={v=>line(i,{source:v})} multiline required maxLength={500}/><Field label={`Source date ${i+1}`} name={`lines.${i}.effective_date`} value={l.effective_date} type="date" onChange={v=>line(i,{effective_date:v})} required/></div><button type="button" className="secondary" onClick={()=>set("lines",value.lines.filter((_,n)=>n!==i))}>Remove line {i+1}</button></fieldset>)}<button type="button" className="secondary" disabled={value.lines.length>=100} onClick={()=>set("lines",[...value.lines,{id:crypto.randomUUID(),description:"",category:"Product",quantity:"",unit:"",unit_cost:"",unit_sell:"",source:"",effective_date:""}])}>Add manual line</button></>;
}
function ProposalTotals({draft}:{draft:Draft}) {
  let totals:ReturnType<typeof calculate>|null=null;
  try {totals=calculate(parseLines(draft.lines));} catch { /* Incomplete proposals never masquerade as saved totals. */ }
  return <aside className="est-totals" aria-label="Proposal totals"><h2>Proposal totals</h2><dl><div><dt>Cost</dt><dd>{money(totals?.cost)}</dd></div><div><dt>Sell</dt><dd>{money(totals?.sell)}</dd></div><div><dt>Difference</dt><dd>{money(totals?.difference)}</dd></div><div><dt>Margin</dt><dd>{totals?.margin_percent==null?"N/A":`${totals.margin_percent}%`}</dd></div><div><dt>Markup</dt><dd>{totals?.markup_percent==null?"N/A":`${totals.markup_percent}%`}</dd></div></dl><p>{totals?.complete?"Calculated from this proposal. Save to create an exact version.":"Complete every line before these amounts can be calculated. A scope-only draft can be saved with no lines."}</p><small>Manual AUD · excluding tax · tax not calculated. Synthetic policy: sell at least cost; unit amounts to 2 places; round each extension HALF_UP to 2 places, then sum.</small></aside>;
}
export function NewEstimate() {
  const data=useCrmResource<Options>("estimating/options");
  return <div className="est-screen"><Link href="/estimating">All estimates</Link><Heading title="New estimate"/><ResourceState {...data}/>{data.data&&<NewEstimateForm options={data.data}/>}</div>;
}
function NewEstimateForm({options}:{options:Options}) {
  const router=useRouter(), params=useSearchParams(), [opportunity,setOpportunity]=useState(()=>options.items.some(o=>o.id===params.get("opportunity"))?params.get("opportunity")!:""),[draft,setDraft]=useState<Draft>({title:"",scope:{included:"",excluded:"",assumptions:""},lines:[]}),[reason,setReason]=useState("");
  const command=useCrmCommand(r=>router.push(`/estimating/estimates/${r.record_id}`));
  if(denied(command.error))return <ErrorNotice error={command.error}/>;
  const frozen=command.busy||command.uncertain;
  return <form onSubmit={e=>{e.preventDefault();void command.send("estimating/estimates",{id:crypto.randomUUID(),opportunity_id:opportunity,owner_id:options.owner_id,...draft,policy:arithmeticPolicy,reason});}}><ValidationFields error={command.error}><fieldset disabled={frozen} className="est-form"><SelectField label="Existing opportunity" name="opportunity_id" value={opportunity} onChange={v=>{setOpportunity(v);command.dirty();}} options={options.items.map(o=>({id:o.id,display_name:`${o.display_number} · ${o.title} · ${o.customer}`}))} required/>{!options.items.length&&<p>No eligible opportunities without an estimate were found. <Link href="/crm/opportunities">Open CRM Sales</Link>.</p>}<p>Estimator: <strong>{options.owner_name}</strong> · Option A · Estimation revision r01</p><DraftFields value={draft} onChange={v=>{setDraft(v);command.dirty();}}/><ProposalTotals draft={draft}/><Field label="Reason for creating this estimate" name="reason" value={reason} onChange={setReason} required maxLength={1000}/><button type="submit">{command.busy?"Saving…":"Create estimate"}</button></fieldset></ValidationFields><CommandState command={command}/><p className="est-note">Unsaved entries are held in this page only. Reloading, navigating away or changing identity discards them.</p></form>;
}
export function EstimateDetail({id}:{id:string}) {
  const [selected,setSelected]=useState<string|null>(null),[accepted,setAccepted]=useState(0),[epoch,setEpoch]=useState(0),[pending,setPending]=useState<"estimate"|"quote"|null>(null);
  const lock=(kind:"estimate"|"quote",active:boolean)=>setPending(current=>active?kind:current===kind?null:current);
  const data=useCrmResource<Detail>(`estimating/estimates/${id}${selected?`?version_id=${selected}`:""}`),d=data.data;
  return <div className="est-screen"><Link href="/estimating">All estimates</Link><ResourceState {...data}/>{d&&<><Heading title={d.saved.title}><span><Status value="Draft"/> · {d.display_number}</span></Heading><p className="est-context">{d.context.customer} · {d.context.site??"Site to be confirmed"} · Estimator {d.context.owner}</p><div className="est-actions"><Link href={`/crm/opportunities/${d.opportunity.id}`}>{d.opportunity.display_number} · Opportunity and follow-up</Link><a href="#estimate-work">Edit scope</a><a href="#estimate-lines">Edit cost lines</a></div><p>Option A · Estimation revision r01 · Viewing saved version {d.saved.version} · Current version {d.version}</p><div className="est-saved" aria-label="Saved totals"><strong>Saved cost {money(d.totals.cost)}</strong><strong>Saved sell {money(d.totals.sell)}</strong><span>Excluding tax</span></div><details className="est-panel"><summary>Saved versions and change reasons ({d.versions.length})</summary>{d.versions.map(v=><p key={v.id}><button className="secondary" disabled={pending!==null} onClick={()=>setSelected(v.id)}>View version {v.version}</button> {v.reason} <small>{new Date(v.created_at).toLocaleString("en-AU")}</small></p>)}<button className="secondary" disabled={pending!==null} onClick={()=>setSelected(null)}>View current version</button></details>{accepted>d.version?<p role="status">Save accepted. Loading the exact saved version…</p>:<EstimateEditor key={`${id}:${selected??"current"}:${epoch}`} detail={d} blocked={pending==="quote"} onPending={active=>lock("estimate",active)} onAccepted={version=>{setAccepted(version);setSelected(null);setEpoch(x=>x+1);data.reload();}}/>}<PrepareDraft key={`quote:${id}:${selected??"current"}:${epoch}`} detail={d} blocked={pending==="estimate"} onPending={active=>lock("quote",active)}/><section className="est-panel"><h2>Draft quotation history</h2>{!d.quotes.length?<p>No draft quotations available.</p>:d.quotes.map(q=><p key={q.id}><Link href={`/estimating/quotes/${q.id}`}>{q.display_number} · Draft revision {q.version}</Link> · {q.render_state}</p>)}</section></>}</div>;
}
function EstimateEditor({detail:d,onAccepted,blocked,onPending}:{detail:Detail;onAccepted:(version:number)=>void;blocked:boolean;onPending:(active:boolean)=>void}) {
  const [draft,setDraft]=useState<Draft>({title:d.saved.title,scope:d.saved.scope,lines:d.saved.lines}),[reason,setReason]=useState(""),[base,setBase]=useState(d.version),[baseSaved]=useState(d.saved.version);
  const command=useCrmCommand(r=>onAccepted(r.record_version),`Saved version ${d.saved.version}`,onPending);
  if(denied(command.error))return <ErrorNotice error={command.error}/>;
  const frozen=blocked||!d.can_edit||command.busy||command.uncertain;
  return <section id="estimate-work" className="est-panel"><h2>Scope and cost workbook</h2>{base!==d.version&&<p className="est-note" role="alert">A newer version is now saved. Your proposal below is retained; compare the current saved version before saving.</p>}{base!==d.version&&<details className="est-panel"><summary>Compare current saved version {d.version} with this proposal</summary><h3>{d.current_saved.title}</h3><p className="est-narrative">{d.current_saved.scope.included}</p><p className="est-narrative">Excluded: {d.current_saved.scope.excluded}</p><p className="est-narrative">Assumptions: {d.current_saved.scope.assumptions}</p>{d.current_saved.lines.map(l=><p key={l.id}>{l.description} · {l.quantity} {l.unit} · Unit cost {money(l.unit_cost)} · Unit sell {money(l.unit_sell)}</p>)}<button type="button" className="secondary" disabled={command.busy||command.uncertain} onClick={()=>{setBase(d.version);command.clearError();command.dirty();}}>Keep my proposal and use current version as its predecessor</button></details>}{baseSaved<d.version&&<p className="est-note">This proposal starts from historical version {baseSaved}. Saving creates a successor of current version {d.version}; explain the reason.</p>}{!d.can_edit&&<p>Read access only. The estimate owner must have current edit permission to save.</p>}<form onSubmit={e=>{e.preventDefault();void command.send(`estimating/estimates/${d.id}`,{expected_version:base,...draft,policy:arithmeticPolicy,reason});}}><ValidationFields error={command.error}><fieldset disabled={frozen} className="est-form"><DraftFields value={draft} onChange={v=>{setDraft(v);command.dirty();}}/><ProposalTotals draft={draft}/><Field label="Change reason" name="reason" value={reason} onChange={v=>{setReason(v);command.dirty();}} required maxLength={1000}/>{d.can_edit&&<button type="submit">{command.busy?"Saving…":"Save new version"}</button>}</fieldset></ValidationFields><CommandState command={command}/></form></section>;
}
function PrepareDraft({detail:d,blocked,onPending}:{detail:Detail;blocked:boolean;onPending:(active:boolean)=>void}) {
  const router=useRouter(),[saved]=useState(d.saved),[base]=useState(d.version),[quoteBase]=useState(d.quotes[0]?.version??0),[choices,setChoices]=useState<QuoteChoice[]>(saved.lines.map(l=>({line_id:l.id,included:true,print:true}))),[reason,setReason]=useState("");
  const command=useCrmCommand(r=>router.push(`/estimating/quotes/${r.record_id}`),"Unsaved",onPending);
  if(denied(command.error))return <ErrorNotice error={command.error}/>;
  const total=quoteAmounts(saved.lines,choices),frozen=blocked||!d.can_prepare||command.busy||command.uncertain;
  return <section className="est-panel"><h2>Prepare a draft quotation</h2>{blocked&&<p role="status">Confirm the workbook save outcome before preparing a quotation.</p>}<p>This uses <strong>saved estimate version {saved.version}</strong>. Unsaved workbook edits above are not included.</p>{!saved.lines.length?<p>Add and save complete lines before preparing a draft.</p>:<form onSubmit={e=>{e.preventDefault();void command.send(`estimating/estimates/${d.id}/quotes`,{id:crypto.randomUUID(),estimate_version_id:saved.id,expected_version:base,expected_quote_version:quoteBase,choices,reason});}}><fieldset className="est-form" disabled={frozen}>{saved.lines.map(l=>{const selected=choices.find(c=>c.line_id===l.id)!;return <div className="est-choice" key={l.id}><strong>{l.description}</strong><label><input type="checkbox" checked={selected.included} onChange={e=>{setChoices(choices.map(c=>c.line_id===l.id?{...c,included:e.target.checked}:c));command.dirty();}}/> Include {l.description}</label><label><input type="checkbox" checked={selected.print} onChange={e=>{setChoices(choices.map(c=>c.line_id===l.id?{...c,print:e.target.checked}:c));command.dirty();}}/> Print {l.description}</label></div>;})}<p>Included lines contribute to the draft price. Included lines with print off appear as one “Included scope allowance”. Excluded lines contribute nothing.</p><p className="est-quote-total"><strong>Draft total {money(total.total)}</strong> · Excluding tax</p><Field label="Draft preparation reason" name="reason" value={reason} onChange={setReason} required maxLength={1000}/>{d.can_prepare?<button type="submit">{command.busy?"Preparing…":"Prepare draft quotation"}</button>:<p>Current quote preparation permission and estimate ownership are required.</p>}</fieldset><CommandState command={command}/></form>}</section>;
}
export function QuoteDetail({id}:{id:string}) {
  const data=useCrmResource<Quote>(`estimating/quotes/${id}`),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(null),q=data.data;
  async function render(){setBusy(true);setError(null);try {await api(`estimating/quotes/${id}/render`,{});data.reload();}catch(e){setError(e);data.reload();}finally{setBusy(false);}}
  if(denied(error))return <ErrorNotice error={error}/>;
  return <div className="est-screen"><ResourceState {...data}/>{q&&<><Heading title={q.snapshot.title}><span className="est-draft">Draft revision {q.snapshot.revision}</span></Heading><p>{q.snapshot.display_number} · {q.snapshot.customer}</p><p className="est-note">Synthetic review copy. Not issued. No customer delivery or acceptance has occurred.</p>{q.estimate_id&&<Link href={`/estimating/estimates/${q.estimate_id}`}>Return to estimate workbook</Link>}<section className="est-panel"><h2>Draft output</h2><p role="status">{q.job.output_available?"Exact HTML and PDF saved":`Output ${q.job.state.toLowerCase()}`} · {q.job.attempts} rendering attempts</p><ErrorNotice error={error}/>{q.job.output_available?<div className="est-actions"><a className="button" href={`/api/v1/estimating/quotes/${id}/file?kind=pdf`} target="_blank" rel="noreferrer">Open draft PDF</a><a className="button secondary" href={`/api/v1/estimating/quotes/${id}/file?kind=html`} target="_blank" rel="noreferrer">Open exact draft HTML</a></div>:q.can_prepare?<button disabled={busy} onClick={()=>void render()}>{busy?"Generating draft…":"Generate or recover exact draft"}</button>:<p>The preparation owner can generate or recover this saved draft.</p>}<p><strong>Draft total {money(q.snapshot.total)}</strong> · Excluding tax · Tax not calculated</p><details><summary>Output history and integrity</summary>{q.attempt_history.map((a,i)=><p key={i}>Attempt {a.attempt} · {a.outcome}{a.code?` · ${a.code}`:""}</p>)}{q.job.hashes&&<dl className="est-hashes"><dt>HTML SHA-256</dt><dd>{q.job.hashes.html}</dd><dt>PDF SHA-256</dt><dd>{q.job.hashes.pdf}</dd></dl>}</details></section><article className="est-paper" aria-label="Draft quotation preview"><p className="est-eyebrow">Customer-safe draft content</p><h2>{q.snapshot.title}</h2><p>{q.snapshot.customer} · {q.snapshot.site??"Site to be confirmed"}</p><h3>Included scope</h3><p className="est-narrative">{q.snapshot.scope.included}</p><table><thead><tr><th>Description</th><th>Quantity</th><th>AUD</th></tr></thead><tbody>{q.snapshot.items.map((i,n)=><tr key={n}><td>{i.description}</td><td>{i.quantity?`${i.quantity} ${i.unit}`:"Included"}</td><td>{i.amount}</td></tr>)}</tbody></table><p className="est-quote-total">Draft total {money(q.snapshot.total)}</p><h3>Excluded scope</h3><p className="est-narrative">{q.snapshot.scope.excluded}</p><h3>Assumptions</h3><p className="est-narrative">{q.snapshot.scope.assumptions}</p></article></>}</div>;
}
