import json
from pathlib import Path
ORG='SYN-ORG-101'
sites={'north':{'id':'SYN-SITE-101','name':'North nursery','address':'18 Example Growers Lane, Exampleville QLD 4000'},'south':{'id':'SYN-SITE-102','name':'South propagation','address':'42 Demonstration Road, Sampleton QLD 4000'}}
records={}
def rec(n,site='north',serial=None):
 i=f'SYN-EQP-{n:03}'
 records[i]={'id':i,'name':'Pump 1' if n in [101,102] else f'Irrigation pump {n-100}','org':ORG,'organisation':'Banksia Demonstration Nurseries','site':site,'location':'Irrigation shed','served':['Block A','Block B','Block C'],'manufacturer':'Example Pumps','model':'EP-40','serial':serial if serial is not None else f'00-EP-{n}','version':1}
 return i
for n in range(101,117):rec(n, 'south' if n in [102,112] else 'north')
records['SYN-EQP-101']['serial']='00-EP-102';records['SYN-EQP-103']['serial']='00-EP-103';records['SYN-EQP-104']['serial']=None
spec=[
('Two pumps share a local name','Duplicate candidates','Equipment','north','keep','SYN-EQP-101',['SYN-EQP-101','SYN-EQP-102'],'Investigating','Current','High','2026-09-18','Different addressed sites and retained nameplates establish two separate physical assets.','Keep separate; retain both stable identities.'),
('Serial transcription needs correction','Identity & serials','Equipment','north','serial','SYN-EQP-101',['SYN-EQP-101','SYN-EQP-102'],'Investigating','Current','High','2026-09-17','A typed serial resembles the South propagation pump. The North nameplate reads 00-EP-101.','Correct the current serial; retain both assets and all history.'),
('Two records may be one physical pump','Duplicate candidates','Equipment','north','consolidation','SYN-EQP-103',['SYN-EQP-103','SYN-EQP-106'],'Investigating','Current','High','2026-09-19','An import produced two canonical records. Evidence requires an Equipment-owner consolidation decision.','Prepare a reviewed consolidation request.'),
('Nameplate evidence is missing','Identity & serials','Equipment','north','serial','SYN-EQP-104',['SYN-EQP-104'],'Needs information','Missing','Normal',None,'The identity label is unreadable. No verified replacement serial has been supplied.','Request a legible nameplate and model confirmation.'),
('Billing address used as site address','Missing context','Customers & Sites','north','site','SYN-EQP-105',['SYN-EQP-105'],'Assigned','Current','Normal','2026-09-20','The billing office was copied into the physical site record. Site operator and bill-to are distinct.','Prepare the physical-location owner request.'),
('Facility parent creates a loop','Relationships','Customers & Sites','north','hierarchy','SYN-EQP-106',['SYN-EQP-106'],'Assigned','Current','High','2026-09-18','Propagation area A points to B; B already points to A. A self-parent, cycle or cross-site reassignment is invalid.','Propose the same-site root; preserve effective history.'),
('Check installed and served locations','Relationships','Equipment','north','relationship','SYN-EQP-107',['SYN-EQP-107'],'Investigating','Current','Normal','2026-09-21','The pump is installed in the irrigation shed and validly serves Blocks A, B and C. An extra South-site link needs owner review.','Remove only the unsupported served-area link via its owner.'),
('ERP key repeats across companies','External mappings','AD-05 Mapping','north','mapping','SYN-EQP-108',['SYN-EQP-108'],'Assigned','Current','High','2026-09-18','C0042 exists under two fictional MYOB companies. A display name or key alone cannot determine the debtor.','Prepare company-scoped mapping reconciliation.'),
('Area units do not match','Units & measures','Source owner','north','unit','SYN-EQP-109',['SYN-EQP-109'],'Needs information','Current','Normal',None,'Source footprint is 1.250 ha; a target field holds 1.250 m². Coverage and rounding require source-owner confirmation.','Retain original precision and request an approved representation.'),
('Import observation is incomplete','Source coverage','AD-06 Migration','north','evidence','SYN-EQP-110',['SYN-EQP-110'],'Needs information','Partial','High','2026-09-17','The import inspected 8 of 12 declared records. Four records are unobserved, not verified clear.','Request completion from the import owner.'),
('Accepted correction has a changed target','Identity & serials','Equipment','north','serial','SYN-EQP-111',['SYN-EQP-111'],'Awaiting domain action','Current','High','2026-09-17','A record changed after independent acceptance. The earlier acceptance remains attached to its exact basis.','Review a successor against the current target.'),
('Comparison counterpart is unavailable','Duplicate candidates','Equipment','north','keep','SYN-EQP-101',['SYN-EQP-101','SYN-EQP-112'],'Needs information','Unavailable','Normal',None,'The second comparison record is no longer in the permitted scope. Resolve access through the record owner.','Request scoped evidence; no bypass through retained links.'),
('Correction response was interrupted','Identity & serials','Equipment','north','serial','SYN-EQP-113',['SYN-EQP-113'],'Awaiting domain action','Current','High','2026-09-17','The mock Equipment receiver applied one correction; the first response was lost. Equivalent attempts remain held.','Look up the original operation result.'),
('Field ownership is not configured','Identity & serials','Equipment','north','serial','SYN-EQP-114',['SYN-EQP-114'],'Needs information','Current','Normal',None,'No fixture field-owner/review policy is configured for this target. Support access is not approval authority.','Prepare a policy clarification for the domain owner.'),
('Candidate recurs on new evidence','Duplicate candidates','Equipment','north','keep','SYN-EQP-115',['SYN-EQP-115','SYN-EQP-116'],'Investigating','Current','Normal','2026-09-20','A previous no-issue decision is retained. A new nameplate observation requires reassessment of that decision.','Review the new evidence without deleting the old outcome.'),
('Serial correction touches prepared work','Identity & serials','Equipment','north','serial','SYN-EQP-116',['SYN-EQP-116'],'Investigating','Current','High','2026-09-18','Current display, a draft visit and an issued pack reference this asset. Only the current field is eligible for correction.','Prepare a service follow-up; preserve issued bytes and acknowledgement.')]
cases=[]
for j,x in enumerate(spec,1):
 title,family,domain,site,kind,target,subjects,state,coverage,priority,due,observation,next_action=x
 evidence=[{'id':f'SYN-SRC-{j:03}','version':1,'title':'Retained nameplate transcription' if kind in ['serial','keep','consolidation'] else 'Retained source observation','owner':domain,'asAt':'2026-09-16T22:00:00Z','text':f'Fictional observed evidence for {target}. '+observation,'available':coverage not in ['Missing','Unavailable']}]
 if j==2:evidence.append({'id':'SYN-SRC-002-B','version':2,'title':'North pump identity confirmation','owner':'Equipment','asAt':'2026-09-17T00:15:00Z','text':'North nursery / Irrigation shed / SYN-EQP-101. Exact nameplate serial: 00-EP-101; model EP-40. Separate from SYN-EQP-102 at South propagation. Fictional evidence.','available':True})
 cases.append({'id':f'DQ-{j:02}','title':title,'family':family,'domain':domain,'site':site,'kind':kind,'target':target,'subjects':subjects,'state':state,'coverage':coverage,'priority':priority,'due':due,'dateReason':'Owner to confirm required date' if due is None else '', 'owner':None if j in [4,9,14] else 'Alex Morgan','created':f'2026-09-{10+j%6:02}T00:00:00Z','observation':observation,'next':next_action,'policy':None if j==14 else 1,'sourceVersion':1,'impactVersion':1,'impactComplete':j!=10,'evidence':evidence,'proposals':[],'findings':[],'decisions':[],'operations':[],'followups':[],'events':[{'id':f'EV-{j}-1','time':'2026-09-16T22:00:00Z','actor':'Fixture observation','action':'Finding recorded','detail':observation}], 'disposition':'Unassessed','outcome':'Not required','privateNotes':{},'origin':f'OBS-20260917-{j:03}','rule':'NAME-01' if family=='Duplicate candidates' else 'CONTEXT-01','ruleVersion':1})
seed={'schema':1,'generation':0,'records':records,'sites':sites,'cases':cases,'ledger':{},'clock':'2026-09-17T02:00:00Z','scan':{'mode':'Complete','run':0,'lastSuccess':'2026-09-17T01:30:00Z'},'issued':{'id':'SYN-PACK-014','version':1,'bytes':'SYNTHETIC ISSUED PACK | SYN-EQP-101 | serial 00-EP-102 | North nursery | issued 2026-09-10','acknowledgement':{'id':'SYN-ACK-014','issue':'SYN-PACK-014','version':1,'actor':'Fictional technician','time':'2026-09-11T00:30:00Z','response':'Acknowledged original issue'}}}
Path('ad03-src/fixtures.json').write_text(json.dumps(seed,ensure_ascii=False,indent=2))
