#!/usr/bin/env python3
"""Assemble the standalone AD-01 Users, Roles, Teams & Access Review design.

The capability list is generated from the application's own `Capability` union and the
hosted-demo capability set, so the design cannot silently drift from the enforced contract.
"""
from pathlib import Path
import hashlib
import json
import re

root = Path(__file__).resolve().parents[1]
source = root / "docs/design/access-review"
target = root / "docs/design/access-review/access-review.html"
permissions = root / "src/platform/permissions.ts"
demo = root / "scripts/demo-database.ts"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def capability_keys() -> list[str]:
    text = permissions.read_text(encoding="utf-8")
    block = re.search(r"export type Capability\s*=(.*?);", text, re.S)
    assert block, "Capability union not found"
    keys = re.findall(r'"([a-z_.]+)"', block.group(1))
    assert keys and len(keys) == len(set(keys)), "Capability union is empty or duplicated"
    return keys


def demo_keys() -> list[str]:
    text = demo.read_text(encoding="utf-8")
    block = re.search(r"export const demoCapabilities\s*=\s*\[(.*?)\]\s*as const", text, re.S)
    assert block, "demoCapabilities not found"
    return re.findall(r'"([a-z_.]+)"', block.group(1))


keys = capability_keys()
hosted = demo_keys()
assert set(hosted) <= set(keys), "Hosted demo capability outside the Capability union"
generated = (
    "/* Generated by scripts/build-access-review.py. Do not edit by hand. */\n"
    "(function(root){'use strict';root.ACCESS_CAPABILITIES=Object.freeze("
    + json.dumps(
        {
            "source": "src/platform/permissions.ts",
            "source_sha256": sha(permissions),
            "demo_source": "scripts/demo-database.ts",
            "demo_source_sha256": sha(demo),
            "keys": keys,
            "hosted_demo": hosted,
        },
        separators=(",", ":"),
    )
    + ");})(globalThis);\n"
)
(source / "capabilities.js").write_text(generated, encoding="utf-8", newline="\n")

html = (source / "template.html").read_text(encoding="utf-8")
for marker, filename in [
    ("FONTS", "fonts.css"),
    ("CSS", "workspace.css"),
    ("CAPABILITIES", "capabilities.js"),
    ("MODEL", "model.js"),
    ("APP", "workspace.js"),
]:
    content = (source / filename).read_text(encoding="utf-8")
    if filename.endswith(".js"):
        content = content.replace("</script", "<\\/script")
    assert html.count(f"/* {marker} */") == 1, marker
    html = html.replace(f"/* {marker} */", content)
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(html, encoding="utf-8", newline="\n")
print(f"{target.relative_to(root)}\nSHA-256 {sha(target)}\nCapabilities {len(keys)} · hosted demo {len(hosted)}")
