import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { localConfig } from "../src/platform/config";
import { transaction } from "../src/platform/database";

// Compare every baseline and added row in the seven load-fixture tables.
// The hashes are evidence only; no synthetic business rows are exported.
export async function performanceFixtureFingerprint() {
  assert.equal(localConfig().database_name, "ppo_synthetic_test");
  assert.equal(process.env.PPO_BENCHMARK_FIXTURE, "add-synthetic-load");
  return transaction(async c => {
    await c.query("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY");
    const tables: { table: string; rows: number; sha256: string }[] = [];
    for (const table of ["organisations", "assets", "asset_location_events", "work_orders", "work_order_tickets", "scope_revisions", "appointments"]) {
      // Identifiers come only from the fixed allowlist above.
      const rows = (await c.query<{ record: string }>(
        `SELECT to_jsonb(t)::text AS record FROM ppo.${table} t WHERE workspace_id=$1 ORDER BY to_jsonb(t)::text`,
        ["10000000-0000-4000-8000-000000000001"],
      )).rows;
      const hash = createHash("sha256");
      for (const row of rows) hash.update(row.record).update("\n");
      tables.push({ table, rows: rows.length, sha256: hash.digest("hex") });
    }
    assert.equal(tables.find(t => t.table === "organisations")?.rows, 1000);
    assert.equal(tables.find(t => t.table === "assets")?.rows, 5000);
    assert.equal(tables.find(t => t.table === "appointments")?.rows, 10000);
    return { tables, scope: "All rows in the seven declared load-fixture tables in the synthetic workspace; excludes authentication/session and audit activity generated by login. No reset, repair, reseed or inferred whole-database equality." };
  });
}
