import {test,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {database,closeDatabase} from '../../src/platform/database';
import {CRM} from '../helpers/crm';
test.beforeAll(()=>{process.loadEnvFile('.env.local');});test.afterAll(closeDatabase);
async function identity(page:Page,profile='coordinator') {
  await expect(page.getByRole('region',{name:'Local demonstration identity',exact:true})).toHaveAttribute('aria-busy','false');
  if(!(await page.getByLabel('Identity',{exact:true}).isVisible()))await page.getByRole('button',{name:'Change identity',exact:true}).click();
  await page.getByLabel('Identity',{exact:true}).selectOption(profile);await page.getByRole('button',{name:'Use this identity',exact:true}).click();
  await expect(page.getByLabel('Identity',{exact:true})).toBeEnabled();
}
test('AI1 desktop and phone: customer search, grounded context, edited review and durable lost-response recovery',async({page},info)=>{
  await page.goto('/assistant');await identity(page);
  await expect(page.getByText('Simulated assistant · Synthetic data only',{exact:true})).toBeVisible();
  const title='SYN Assisted '+randomUUID().slice(0,8);
  await page.getByLabel('Your request',{exact:true}).fill(`Add a deal for SYN to inspect irrigation controls\nTitle: ${title}\nRequirement: SYN confirm controls requirements\nSource: Phone\nSource details: SYN demonstration conversation\nFollow-up: SYN arrange a discovery call`);
  await page.getByRole('button',{name:'Send request',exact:true}).click();
  const row=page.locator('.assistant-records li').filter({has:page.locator(`a[href="/customers/${CRM.org}"]`)});
  await row.getByRole('button',{name:'Select customer',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Customer CRM summary',exact:true})).toBeVisible();
  await expect(page.locator('.assistant-facts a').first()).toHaveAttribute('href',`/customers/${CRM.org}`);
  await expect(page.getByText(/Service, equipment, projects, email and Finance are outside/)).toBeVisible();
  await page.getByLabel('Site',{exact:true}).selectOption(CRM.site);
  await page.getByLabel('Primary contact',{exact:true}).selectOption(CRM.person);
  await page.getByLabel('Opportunity owner',{exact:true}).selectOption(CRM.owner);
  await page.getByLabel('Follow-up owner',{exact:true}).selectOption(CRM.owner);
  const knownDate=info.project.name==='desktop-chromium';
  await page.getByLabel('Follow-up due date',{exact:true}).selectOption(knownDate?'known':'unknown');
  if(knownDate)await page.getByLabel('Due date and time with UTC offset',{exact:true}).fill('2026-09-15T09:00:00+10:00');
  await page.getByRole('button',{name:'Prepare review',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Review opportunity',exact:true})).toBeFocused();
  await page.getByRole('button',{name:'Edit and review again',exact:true}).click();
  await page.getByLabel('Opportunity title',{exact:true}).fill(title+' edited');
  await page.getByRole('button',{name:'Prepare review',exact:true}).click();
  await expect(page.locator('.assistant-review-details')).toContainText(title+' edited');
  await expect(page.locator('.assistant-review-details')).toContainText(knownDate?'2026-09-14T23:00:00.000Z':'Due date needed');
  const proposalURL=page.url(),id=new URL(proposalURL).searchParams.get('proposal')!;
  expect((await database().query('SELECT count(*)::int n FROM ppo.opportunities WHERE title=$1',[title+' edited'])).rows[0].n).toBe(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:info.outputPath('AI1-reviewed-opportunity.png'),fullPage:true});
  let dropped=false;
  await page.route(`**/assistant/proposals/${id}/confirm`,async route=>{const response=await route.fetch();expect(response.ok()).toBe(true);dropped=true;await route.abort('failed');});
  await page.getByRole('button',{name:'Confirm and create opportunity',exact:true}).click();
  await expect.poll(()=>dropped).toBe(true);
  await expect(page.getByRole('button',{name:'Retry original submission',exact:true})).toBeVisible();
  await page.unroute(`**/assistant/proposals/${id}/confirm`);
  await page.reload();
  await expect(page.getByRole('heading',{name:'Opportunity saved',exact:true})).toBeVisible();
  expect((await database().query('SELECT count(*)::int n FROM ppo.opportunities WHERE title=$1',[title+' edited'])).rows[0].n).toBe(1);
  const action=(await database().query('SELECT a.due_at,a.due_needed FROM ppo.opportunities o JOIN ppo.activities a ON a.workspace_id=o.workspace_id AND a.id=o.next_activity_id WHERE o.title=$1',[title+' edited'])).rows[0];
  expect(action.due_needed).toBe(!knownDate);expect(action.due_at?.toISOString()??null).toBe(knownDate?'2026-09-14T23:00:00.000Z':null);
  expect(await page.evaluate(()=>[...Object.keys(localStorage),...Object.keys(sessionStorage)].filter(k=>/assistant|proposal|chat/i.test(k)))).toEqual([]);
  await page.screenshot({path:info.outputPath('AI1-recovered-save.png'),fullPage:true});
  await identity(page,'second-company');
  await expect(page.getByRole('link',{name:'Open saved opportunity',exact:true})).toHaveCount(0);
  await expect(page.locator('.assistant-review-details')).toHaveCount(0);
  await expect(page.getByText(title+' edited',{exact:true})).toHaveCount(0);
});
test('AI1 keyboard, narrow screen and late responses clear when identity changes',async({page},info)=>{
  await page.goto('/assistant');await identity(page);await page.setViewportSize({width:320,height:844});
  await expect(page.getByLabel('Your request',{exact:true})).toBeEnabled();
  let release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve;});let requested=false;
  await page.route('**/assistant/turn',async route=>{const response=await route.fetch();requested=true;await held;await route.fulfill({response});});
  await page.getByLabel('Your request',{exact:true}).fill('Find customer SYN');await page.getByRole('button',{name:'Send request',exact:true}).focus();await page.keyboard.press('Enter');
  await expect.poll(()=>requested).toBe(true);await identity(page,'second-company');release();
  await expect(page.getByRole('heading',{name:'Matching customers',exact:true})).toHaveCount(0);
  await expect(page.getByLabel('Your request',{exact:true})).toHaveValue('');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:info.outputPath('AI1-320px-identity-cleared.png'),fullPage:true});
});
