// One installation contract for the application head, the separate sign-in document,
// the hosted gateway and the checks. Installation adds no offline capability and no
// new identity: it only lets a device keep an icon that opens the existing app.

export const navy = "#242a37";
export const canvas = "#f5f6f8";

/** Generated by the Next.js manifest file convention in src/app/manifest.ts. */
export const manifestPath = "/manifest.webmanifest";
/** A stable relative identity and start that survive UI releases on this origin. */
export const appIdentity = "/";
export const appStart = "/work";

export const appleTouchIconPath = "/pwa/ppo-app-icon-180.png";

/** W3C icon masks: artwork must stay inside a central circle of radius 40% of the width. */
export const maskableSafeFraction = 0.4;

/**
 * Real same-origin PNG exports of the issued logo pack. `manifest` marks the ones the
 * web app manifest declares; the 180 px export is the Apple touch icon, which Apple
 * reads from the document link rather than from the manifest.
 */
export const installationIcons = [
  { path: "/pwa/ppo-app-icon-192.png", sizes: "192x192", type: "image/png", purpose: "any", manifest: true },
  { path: "/pwa/ppo-app-icon-512.png", sizes: "512x512", type: "image/png", purpose: "any", manifest: true },
  { path: "/pwa/ppo-app-icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable", manifest: true },
  { path: appleTouchIconPath, sizes: "180x180", type: "image/png", purpose: "any", manifest: false },
] as const;

/**
 * The only paths the hosted gateway serves without resolving a business identity.
 * A browser and an operating system read these before any session exists, so they
 * must not depend on one. Exact strings only: no prefix, directory or wildcard.
 */
export const publicInstallationAssets: readonly string[] = [
  manifestPath,
  ...installationIcons.map((icon) => icon.path),
];

/** Safe reads of exactly those paths. Anything else keeps the existing identity gate. */
export function publicInstallationAsset(method: string, pathname: string): boolean {
  return (
    (method === "GET" || method === "HEAD") &&
    publicInstallationAssets.includes(pathname)
  );
}
