import { randomUUID } from 'node:crypto';
import { createWorkOrder,saveWorkScope,readWorkOrder,assessWorkReadiness,authoriseWorkOrder,proposeVisit } from '../../src/service/work-orders';
import { recordContact,readAppointment,confirmAppointment } from '../../src/scheduling/planner';
import { createPack,checkPack,requestIssue,readPack,acknowledgePack } from '../../src/documents/packs';
import { processRenderJob } from '../../src/documents/worker';
import { readFieldJob } from '../../src/field/reads';
import { startAttendance } from '../../src/field/start';
import { base,principal,id,content } from './packs';
import { startInput } from './field';
export async function twoTaskStarted(){
const co=await principal(),wid=randomUUID(),aid=randomUUID(),pid=randomUUID();
await createWorkOrder(co,{...base(),id:wid,company_id:id('20'),site_id:id('70'),customer_id:id('50'),service_owner_id:co.actor_id,tickets:[{ticket_id:id('40',20),issue_disposition:'SYN two separate task outcomes need field evidence'}]});
const evidence={title:'SYN two-task visual authority',content_text:'SYN limited non-intervention external inspection and identification. No financial approval.',source_reference:'SYN-PPO-P07-TWO-TASKS',source_version:'1'};
let w=(await readWorkOrder(co,wid)).items[0];
await saveWorkScope(co,wid,{...base(),expected_version:w.version,scope:{summary:'SYN inspect controller and identify uncertain external equipment',exclusions:'No shutdown, repair, energised access, replacement or extra work.',diagnostic_limit:'External observation and identification only.',pending_account_plan:'SYN service owner resolves account questions; Finance independent.',authority_evidence:evidence,coverage:{status:'Disputed',agreement_reference:null,source_version:null,effective_from:null,effective_to:null,assessment:'SYN coverage remains unresolved',reason:'SYN no verified agreement',charging_route:'FinanceReview'},items:[{task_kind:'Inspection',task_description:'SYN inspect external controller display',expected_outcome:'Record observed condition',completion_requirements:['Record findings','Stop before intervention'],required_skill_codes:['SYN-VISUAL'],shutdown_condition:null,access_condition:null,assets:[{asset_id:id('80'),configuration_id:null,identification_plan:null}]},{task_kind:'Identification',task_description:'SYN identify uncertain external equipment',expected_outcome:'Retain uncertain identity until the controlled process resolves it',completion_requirements:['Record candidates and remaining questions','No intervention'],required_skill_codes:['SYN-VISUAL'],shutdown_condition:null,access_condition:null,assets:[{asset_id:id('80',2),configuration_id:null,identification_plan:{method:'SYN read external plate and compare exact documents',limits:'No opening, adjustment, shutdown or energised access'}}]}]}});
w=(await readWorkOrder(co,wid)).items[0];const scope=w.scopes.find(s=>s.id===w.scope_revision_id)!;
for(const criterion_code of ['SiteAccess','SiteControls','CompetencyPlan','MandatoryIsolation','ShutdownAuthority']){w=(await readWorkOrder(co,wid)).items[0];await assessWorkReadiness(co,wid,{...base(),expected_version:w.version,assessment:{scope_revision_id:scope.id,scope_version:scope.version,criterion_code,outcome:['MandatoryIsolation','ShutdownAuthority'].includes(criterion_code)?'NotApplicable':'Pass',reason:'SYN reviewed exact external non-intervention scope',evidence,source_as_at:'2026-09-05T00:00:00Z'}});}
w=(await readWorkOrder(co,wid)).items[0];await authoriseWorkOrder(co,wid,{...base(),expected_version:w.version,scope_revision_id:scope.id,scope_version:scope.version,policy_version_id:scope.policy_version_id});
w=(await readWorkOrder(co,wid)).items[0];await proposeVisit(co,wid,{...base(),id:aid,expected_version:w.version,scope_revision_id:scope.id,scope_version:scope.version,start_at:'2026-12-04T00:00:00Z',end_at:'2026-12-04T02:00:00Z',customer_commitment:'Proposed',preparation_status:'Preparing'});
w=(await readWorkOrder(co,wid)).items[0];await assessWorkReadiness(co,wid,{...base(),expected_version:w.version,assessment:{scope_revision_id:scope.id,scope_version:scope.version,appointment_id:aid,criterion_code:'ToolPreparation',outcome:'Pass',reason:'SYN reviewed fictional visual inspection kit',evidence,source_as_at:'2026-09-05T00:00:00Z'}});
let a=(await readAppointment(co,aid)).items[0];await recordContact(co,aid,{...base(),id:randomUUID(),expected_version:a.version,recipient_id:id('60'),channel:'Simulated',outcome:'Confirmed',occurred_at:new Date().toISOString(),notes:'SYN manually recorded customer date agreement'});
a=(await readAppointment(co,aid)).items[0];await confirmAppointment(co,aid,{...base(),expected_version:a.version,expected_work_order_version:a.work_order_version,expected_assignment_version:a.assignment_version,scope_revision_id:scope.id,scope_version:scope.version,policy_version_id:scope.policy_version_id,scheduling_policy_id:id('a0'),scheduling_policy_version:1,crew:[9,2].map((n,i)=>({resource_id:id('a4',n),resource_version:1,calendar_version:1,crew_role:i?'Technician':'Lead',travel_before_minutes:0,travel_after_minutes:0,travel_reason:'SYN explicitly zero same-site allowance'}))});
a=(await readAppointment(co,aid)).items[0];await createPack(co,{...base(),id:pid,appointment_id:aid,expected_appointment_version:a.version,content:content()});let pack=(await readPack(co,pid)).items[0];await checkPack(co,pid,{...base(),expected_version:pack.version,decision:'Checked'});pack=(await readPack(co,pid)).items[0];await requestIssue(co,pid,{...base(),expected_version:pack.version});pack=(await readPack(co,pid)).items[0];await processRenderJob(pack.jobs[0].id);pack=(await readPack(co,pid)).items[0];
for(const profile of ['assigned-technician','second-technician']){const p=await principal(profile),r=pack.readiness.recipients.find((r:{user_id:string})=>r.user_id===p.actor_id)!;await acknowledgePack(p,pack.current_issue_id!,{...base(),assignment_id:r.assignment_id,assignment_version:r.assignment_version,presented_hash:pack.issues[0].output_hash,captured_at:new Date().toISOString()});}
const p=await principal('assigned-technician'),job=(await readFieldJob(p,aid)).items[0];await startAttendance(p,aid,startInput(job));return {p,co,job:(await readFieldJob(p,aid)).items[0]};
}
